## Assignment 1

1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 
8.10.
a. Now in the ‘myList’, append these values: 30,40 
b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [7]:
mylist=[10,20,30,'apple',True,8.10]

In [8]:
mylist.append(30)

In [10]:
mylist.append(40)

In [11]:
reversedList=mylist[::-1]

In [12]:
reversedList

[40, 30, 8.1, True, 'apple', 30, 20, 10]

2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
a. After that eliminate the ‘text’ value form the dictonary.
b. Add ‘features’ in the dictonary.
c. Fetch the ‘data’ element from the dictonary and display it in the output.

In [13]:
mydict={1:'Data',2:'Information',3:'Text'}

In [14]:
mydict

{1: 'Data', 2: 'Information', 3: 'Text'}

In [17]:
del_value='Text'
for key ,value in mydict.items():
    if value==del_value:
        del mydict[key]
        break
print(mydict)

{1: 'Data', 2: 'Information'}


In [18]:
mydict[3]='features'
print(mydict)

{1: 'Data', 2: 'Information', 3: 'features'}


In [25]:
print(mydict.get(1))

Data


3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [26]:
mytuple=(1,2,3,'apple','mango')

In [27]:
mytuple

(1, 2, 3, 'apple', 'mango')

4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
a. Find the minimum value from the numeric_tuple.
b. Concatenate my_tuple with numeric_tuple and store the result in r1.
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [28]:
numeric_tuple=(10,20,30,40,50)

In [29]:
min(numeric_tuple)

10

In [30]:
r1=mytuple+numeric_tuple

In [31]:
r1

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)

In [33]:
from copy import deepcopy
newdupli=deepcopy(mytuple)

In [34]:
newdupli

(1, 2, 3, 'apple', 'mango')

In [40]:
newdupli=mytuple*2

In [41]:
newdupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to 
contains{2,3,7,6,1}
a. Perform the below operation:
a. set1 union set2
b. set1 intersection set2 
c. set1 difference set2

In [42]:
set1={1,2,3,4,5}


In [43]:
set1

{1, 2, 3, 4, 5}

In [45]:
set2={2,3,7,6,1}

In [46]:
set2

{1, 2, 3, 6, 7}

In [47]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [48]:
set1.intersection(set2)

{1, 2, 3}

In [49]:
set1.difference(set2)

{4, 5}

## Assignment 2

1. create a 3*3 matrix value ranging from 2 to 10

In [50]:
import numpy as np

In [51]:
x=np.arange(2,11).reshape(3,3)

In [52]:
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
y=np.array([[2,3,4],[5,6,7],[8,9,10]])

In [54]:
y

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


In [55]:
arr=np.array([[1,2,3,4]])

In [56]:
arr

array([[1, 2, 3, 4]])

In [57]:
converted_arr=arr.astype(np.float)

In [58]:
converted_arr

array([[1., 2., 3., 4.]])

3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [59]:
numpy_arr=np.array([10,20,30])

In [60]:
numpy_arr

array([10, 20, 30])

In [61]:
numpy_arr=np.append(numpy_arr,[40,50,60,70,80,90])

In [62]:
numpy_arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

4. Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.

In [63]:
arr1=np.array([1,2,3,4])

In [64]:
arr2=np.array([5,6,7,8])

In [65]:
sumarray=arr1+arr2

In [66]:
sumarray

array([ 6,  8, 10, 12])

5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array

In [70]:
arr_1=np.arange(10,100,10).reshape(3,3)

In [71]:
arr_1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
arr_1[0]

array([10, 20, 30])

In [74]:
arr_1[2,2]

90